[versions]
agp = "8.3.0-alpha03"
kotlin = "1.9.10"
core-ktx = "1.10.1"
appcompat = "1.6.1"
material = "1.9.0"
xposed = "82"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

